[tool.portray]
docs_dir = "documentation"
extra_dirs = ["examples", "artwork"]

[tool.portray.mkdocs.theme]
favicon = "artwork/koala.png"
logo = "artwork/koala.png"
name = "material"
palette = {primary = "blue grey", accent = "green"}
